In [105]:
import pandas as pd
df = pd.read_csv("data.csv")
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [106]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [107]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [108]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [109]:
df["Review Rating"] = df.groupby("Category")["Review Rating"].transform(lambda x: x.fillna(x.mean()))
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [110]:
df.columns = df.columns.str.lower().str.replace(" ","_")
df = df.rename(columns={'purchase_amount_(usd)' : 'purchase_amount'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [111]:
# create age group using qcut
age_type = ['young','adult', 'middle-aged', 'senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=age_type)
df["age_group"].head(10)

0    middle-aged
1          young
2    middle-aged
3          young
4    middle-aged
5    middle-aged
6         senior
7          young
8          young
9    middle-aged
Name: age_group, dtype: category
Categories (4, str): ['young' < 'adult' < 'middle-aged' < 'senior']

In [112]:
# create columns purchase_frequency_days
frequency_mapping = {
    'fortnightly': 14,
    'monthly': 30,
    'weekly': 7,
    'quarterly': 90,
    'bi-weekly': 14,
    'annually': 365,
    'every 3 months': 90
}
df['frequency_of_purchases'] = df['frequency_of_purchases'].str.lower()
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)
df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            fortnightly
1                       14            fortnightly
2                        7                 weekly
3                        7                 weekly
4                      365               annually
5                        7                 weekly
6                       90              quarterly
7                        7                 weekly
8                      365               annually
9                       90              quarterly

In [113]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [114]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchase_frequency_days'],
      dtype='str')

In [115]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              3900 non-null   int64
 1   age                      3900 non-null   int64
 2   gender                   3900 non-null   str
 3   item_purchased           3900 non-null   str
 4   category                 3900 non-null   str
 5   purchase_amount          3900 non-null   int64
 6   location                 3900 non-null   str
 7   size                     3900 non-null   str
 8   color                    3900 non-null   str
 9   season                   3900 non-null   str
 10  review_rating            3900 non-null   float64
 11  subscription_status      3900 non-null   str
 12  shipping_type            3900 non-null   str
 13  discount_applied         3900 non-null   str
 14  promo_code_used          3900 non-null   str
 15  previous_purchases       3900 non-null   int64
 16  payment_method           3900 non-null   str
 17  frequency_of_purchases   3900 non-null   str
 18  age_group                3900 non-null   category
 19  purchase_frequency_days  3900 non-null   int64
dtypes: category(1), float64(1), int64(5), str(13)
memory usage: 583.0 KB

In [116]:
df = df.drop('discount_applied',axis = 1)

In [ ]:
#CODE TO CONNECT TO MY SQL DATABASE
# !pip install mysql-connector-python
import mysql.connector

# Connect to MySQL
conn = mysql.connector.connect(
    host="localhost",        # use localhost if MySQL is installed on your laptop
    user="root",             # your MySQL username
    password="rakshithvinay56",# your MySQL password
    database="data_analysis"       # your database name
)

# Check connection
if conn.is_connected():
    print("Connected to MySQL successfully!")

# Create cursor
cursor = conn.cursor()

# Run a query
cursor.execute("SELECT * FROM your_table")

# Fetch and print data
for row in cursor.fetchall():
    print(row)

# Close connection
cursor.close()
conn.close()

ProgrammingError: 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)